### ISSUE TITLE
Chạy mainnet

### ISSUE THREAD

**Issue by 0x00trust** [BHONetwork/bholdus-chain#80]
Chào ad
Mình có VPS rảnh nên đang chạy mainnet của BHO
Mình có thể làm gì với nó?

cargo build --features with-ulas-runtime --release
./target/release/bholdus --chain=ulas

**Comment by dpryde258** [comment]
Hi @0x00trust, I would like to answer this question in English.

As we stated in our wpp, BHO Chain (BHC) is a Nominated Proof of Stake blockchain. However, in the early stage, we only support Proof of Staked Authority (private authorities). Hence, the only thing you can do is start a RPC node with your VPS.

We will update the README and will get back to you later with the comprehensive guide.

**Comment by dpryde258** [comment]
Hi @0x00trust, we just updated the README. You can follow the guide there.

You can use pre-built binary for Mainnet
https://github.com/BHONetwork/bholdus-chain/releases/tag/ulas-v1.0.15
